<?php

namespace App\Utils;

class InspiringPT
{
    public static function quote(): string
    {
        $frases = [
            // 🌟 Bíblicas
            'Tudo posso naquele que me fortalece. (Filipenses 4:13)',
            'O Senhor é meu pastor e nada me faltará. (Salmo 23:1)',
            'Entregue o seu caminho ao Senhor; confie nele, e ele agirá. (Salmo 37:5)',
            'Porque sou eu que conheço os planos que tenho para vocês. (Jeremias 29:11)',
            'Em tudo dai graças. (1 Tessalonicenses 5:18)',
            'Sede fortes e corajosos. (Josué 1:9)',
            'Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia. (Salmo 46:1)',
            'Não temas, porque eu sou contigo. (Isaías 41:10)',
            'A fé move montanhas. (Mateus 17:20)',
            'Com Deus faremos proezas. (Salmo 60:12)',

            // 🧠 Carl Gustav Jung
            'Conheça todas as teorias, domine todas as técnicas, mas ao tocar uma alma humana, seja apenas outra alma humana.',
            'Quem olha para fora sonha, quem olha para dentro desperta.',
            'Até você se tornar consciente, o inconsciente irá dirigir sua vida e você vai chamá-lo de destino.',
            'Aquilo a que você resiste, persiste.',
            'A liberdade se estende apenas até onde vai o conhecimento do seu inconsciente.',
            'Solidão não é a ausência de pessoas, é a impossibilidade de se comunicar com elas.',
            'Sua visão se tornará clara apenas quando você olhar dentro do seu coração.',
            'Não segure alguém que quer partir, pois assim você impede quem deseja chegar.',
            'Onde o amor impera, não há desejo de poder.',
            'A maior tragédia da vida é tornar-se aquilo que os outros esperam que você seja.',

            // ✨ Frases inspiradoras e motivacionais
            'Você é mais forte do que pensa.',
            'Coragem é ir mesmo com medo.',
            'Não espere por oportunidades, crie-as.',
            'O fracasso é apenas o tempero que dá sabor ao sucesso.',
            'A ação é a chave fundamental de todo sucesso.',
            'Faça o que puder, com o que tiver, onde estiver.',
            'Grandes coisas nunca vêm da zona de conforto.',
            'Seja o tipo de pessoa que você gostaria de conhecer.',
            'Sucesso é a soma de pequenos esforços repetidos diariamente.',
            'Tenha fé no processo.',
            'Quando tudo parecer difícil, lembre-se por que começou.',
            'Você nasceu para vencer, não para desistir.',
            'O tempo passa de qualquer jeito, invista em você.',
            'Não desista. Geralmente é a última chave que abre a fechadura.',
            'É possível mudar a própria história em qualquer capítulo.',
            'Disciplina é liberdade.',
            'Transforme obstáculos em aprendizado.',
            'Mais importante do que chegar rápido é não parar.',
            'Seja constante. Até o rio fura a pedra de tanto insistir.',
            'Um passo de cada vez ainda é progresso.',
            'Não tenha pressa, tenha direção.',
            'O melhor investimento sempre será em você mesmo.',
            'Quem planta esforço, colhe resultado.',
            'Você não precisa ver a escada inteira, apenas o próximo degrau.',
            'Acredite: você vai conseguir.',
            'Desistir não é uma opção.',
            'Quem acredita, alcança.',
            'Seja melhor do que ontem.',
            'Você não está atrasado. Seu tempo é único.',
            'A mudança começa com uma escolha.',
            'Não espere pela motivação. Aja com disciplina.',
            'A dor é temporária, o resultado é eterno.',
            'Falhar é uma etapa, não um destino.',
            'Toda crise esconde uma oportunidade.',
            'Se não der certo de primeira, tente de novo com mais inteligência.',
            'Você é o autor da sua própria história.',
            'Tenha coragem para ser quem você nasceu para ser.',
            'O impossível é só questão de opinião.',
            'A vida recompensa quem insiste.',
            'Desafios constroem gigantes.',
            'Você nunca saberá do que é capaz até tentar.',
            'Continue, mesmo que pareça lento.',
            'Hoje você planta, amanhã colhe.',
            'Pessoas comuns com disciplina fazem coisas extraordinárias.',
            'A vitória é de quem não desiste.',
            'Seu foco determina sua realidade.',
            'Confie no tempo de Deus.',
            'Você está mais perto do que pensa.',
            'Dificuldades preparam pessoas comuns para destinos extraordinários.',
            'Acredite. Trabalhe. Conquiste.',
            'Persistência é o caminho do êxito.',
            'Seu esforço vale a pena.',
            'Você não está sozinho nessa jornada.',
            'Siga em frente, mesmo com medo.',
            'Lembre-se: você já venceu batalhas piores.',
            'Tudo que você precisa está dentro de você.',
            'O segredo é nunca parar de tentar.',
            'Vá no seu tempo, mas não pare.',
            'Você merece o melhor. Não aceite menos.',
            'Coloque Deus à frente e tudo dará certo.',
            'O bem que você faz volta em dobro.',
            'Permaneça firme, os frutos virão.',
            'Não subestime o poder de um pequeno recomeço.',
            'Cada cicatriz é uma história de superação.',
            'Quando você muda, tudo muda.',
            'Não deixe que o medo decida seu futuro.',
            'Suas atitudes determinam seu sucesso.',
            'O esforço de hoje é o sucesso de amanhã.',
            'Continue, mesmo sem aplausos.',
            'Você é luz, não se esconda.',
            'Ninguém cresce sem dor. Evoluir dói, mas vale.',
            'Faça com excelência o que está em suas mãos.',
            'A vida sorri para quem tem coragem.',
            'Ore, confie e aja.',
            'Sua fé é maior que seu medo.',
            'Lute pelo que te faz feliz.',
            'Você é capaz de recomeçar quantas vezes for necessário.',
            'Sonhe alto. Trabalhe duro. Acredite sempre.',

            // trabalho
            'O trabalho duro supera o talento quando o talento não trabalha duro.',
            'Nada resiste ao trabalho diário e constante.',
            'Quem planta com esforço, colhe com honra.',
            'Com dedicação e foco, tudo é possível.',
            'Não é sobre sorte, é sobre esforço diário.',
            'O sucesso é construído com suor, disciplina e paciência.',
            'Enquanto você descansa, alguém está trabalhando pelo mesmo sonho.',
            'Quem trabalha com garra, colhe com orgulho.',
            'A persistência transforma sonhos em conquistas.',
            'Grandes conquistas exigem grandes esforços.',
            'Não pare quando estiver cansado, pare quando tiver terminado.',
            'Com esforço hoje, vem a recompensa amanhã.',
            'O impossível é só questão de tempo e trabalho.',
            'Trabalhe em silêncio, deixe o sucesso fazer barulho.',
            'Nada acontece sem trabalho. Mas com ele, tudo pode acontecer.',
            'Quem trabalha com propósito, conquista com excelência.',
            'Disciplina vence motivação. Todos os dias.',
            'A vitória é construída nas horas em que ninguém está vendo.',
            'Suor de hoje é a medalha de amanhã.',
            'O que diferencia os vencedores é a constância no esforço.',
            'Trabalhar duro não garante tudo, mas sem isso não se conquista nada.',
            'Quem trabalha com amor, multiplica os resultados.',
            'A recompensa vem para quem insiste, persiste e não desiste.',
            'Sonhar é o primeiro passo. Trabalhar é o caminho.',
            'Nada substitui o poder do trabalho honesto e bem feito.',
            'De grão em grão, com esforço, se constrói uma colheita de vitórias.',
            'O progresso nasce da consistência.',
            'Todo resultado extraordinário vem de atitudes comuns feitas com excelência.',
            'Trabalhe duro agora para viver melhor depois.',
            'Os frutos do trabalho são sempre mais doces.',
            'Seu sucesso será proporcional ao seu esforço.',
            'Trabalhar com coragem é o maior investimento que você pode fazer.',
            'A força de vontade é o motor. O trabalho é o combustível.',
            'A escada do sucesso é feita de degraus de esforço.',
            'Não existe mágica. Existe trabalho com propósito.',
            'Trabalhe tanto até que você nem precise dizer nada: os resultados falam.',
            'Quem foca no processo, inevitavelmente alcança o sucesso.',
            'Levanta, trabalha, conquista.',
            'Trabalhar duro hoje é liberdade amanhã.',
            'O que vem fácil, vai fácil. O que vem com esforço, permanece.',
            'Trabalhar por um sonho é transformar fé em ação.',
            'Com paciência e trabalho, até pedra vira diamante.',
            'Sonho sem trabalho é ilusão. Trabalho sem sonho é prisão. Os dois juntos? Revolução.',
            'A diferença entre quem chega lá e quem para no meio é o trabalho.',
            'Trabalhe como se alguém estivesse tentando tirar tudo de você. Porque está.',
            'Com fé, foco e muito trabalho, o impossível se torna realidade.',
            'Trabalho duro é o maior atalho que existe.',
            'Nenhuma vitória é por acaso. Todas vêm com suor.',
            'Com esforço e fé, você constrói o que quiser.',
            'Trabalhar é semear. O sucesso é a colheita.',

            // Superacao
            'Nenhuma tempestade dura para sempre.',
            'Você já superou dias difíceis antes. Vai vencer de novo.',
            'A dor que você sente hoje é a força que vai te mover amanhã.',
            'O fundo do poço é o ponto de partida para a escalada.',
            'As maiores vitórias vêm depois das batalhas mais difíceis.',
            'Cada cicatriz conta uma história de superação.',
            'Nada é mais forte que um coração que decidiu não desistir.',
            'Levante-se. Você ainda tem muito o que viver.',
            'Não importa o quão devagar você vá, desde que não pare.',
            'A força não vem da vitória, mas da superação.',
            'Você não veio até aqui para parar agora.',
            'A vida testa os fortes. Os que caem e levantam.',
            'Crescer dói, mas ficar parado dói mais.',
            'Você é prova viva de que a superação é possível.',
            'As quedas te ensinaram a voar.',
            'A superação começa quando você diz: eu consigo.',
            'Quando tudo parece desabar, Deus está construindo algo novo.',
            'Não desista. O que te espera é maior do que o que te feriu.',
            'O fracasso só vence quem para de tentar.',
            'Toda dor tem um propósito. E você vai entender lá na frente.',

            // Jesus
            'Jesus é o caminho, a verdade e a vida.',
            'Com Jesus, até o impossível se torna possível.',
            'O que é impossível para o homem é possível para Deus.',
            'Deus nunca erra. Ele tem planos maiores que os seus.',
            'Jesus transforma lágrimas em força e dor em fé.',
            'A presença de Jesus é maior que qualquer tempestade.',
            'Onde Jesus está, há paz, há força, há vitória.',
            'Entregue, confie, espere. Jesus nunca falha.',
            'A mão de Deus nunca chega atrasada.',
            'Jesus não te prometeu ausência de luta, mas garantiu a vitória.',
            'O amor de Jesus é a cura que o mundo precisa.',
            'Com Jesus, você não apenas vence: você testemunha.',
            'Nenhum obstáculo é maior que o nome de Jesus.',
            'Jesus está contigo nos dias bons e principalmente nos difíceis.',
            'A cruz não foi o fim. Foi o começo de uma nova vida.',
            'Jesus não abandona. Ele sustenta.',
            'A fé em Jesus é o combustível da esperança.',
            'Não existe noite que Jesus não possa iluminar.',
            'Com Jesus, até o deserto floresce.',
            'Quando você não vê saída, Jesus abre um caminho.',

        ];

        return $frases[array_rand($frases)];
    }
}
